server:
    port: 9083
    contextPath: /auth-service
    tomcat:
      accesslog:
        enabled: true
        directory: target/tomcat

management:
  context-path: /auth-service/management
  port: 7083
  security:
    enabled: false

spring:
    datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/oauth2-demo?useSSL=false
        username: root
        password: dbpass
        initialize: false

security:
    basic:
        enabled: false
    sessions: stateless
     
logging:
 level:
  org.springframework.security: DEBUG

# custom configuration
authorization:
    accessTokenValiditySeconds: 1200
    refreshTokenValiditySeconds: 1200
    reuseRefreshToken: false
    supportRefreshToken: true